Parameter Play

Instructions

There are a lot of parameters that are set by default when working with these classifiers. Intellisense in VS Code can help you dig into them. Adopt one of the ML Classification Techniques in this lesson and retrain models tweaking various parameter values. Build a notebook explaining why some changes help the model quality while others degrade it. Be detailed in your answer.

From our previous lesson using the cuisine dataset

importing the necessary libraries

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report, precision_recall_curve
import numpy as np

In [17]:
import pandas as pd

cuisines_df = pd.read_csv("../data/cleaned_cuisines.csv")
cuisines_df.head()

,Unnamed: 0,cuisine,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,indian,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,3,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,indian,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [18]:
cuisines_label_df = cuisines_df['cuisine']
cuisines_label_df.head()

0    indian
1    indian
2    indian
3    indian
4    indian
Name: cuisine, dtype: object

In [19]:
cuisines_feature_df = cuisines_df.drop(['Unnamed: 0', 'cuisine'], axis=1)
cuisines_feature_df.head()

,almond,angelica,anise,anise_seed,apple,apple_brandy,apricot,armagnac,artemisia,artichoke,...,whiskey,white_bread,white_wine,whole_grain_wheat_flour,wine,wood,yam,yeast,yogurt,zucchini
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

Split training and test data

In [20]:
from sklearn.model_selection import train_test_split, cross_val_score

X_train, X_test, y_train, y_test = train_test_split(cuisines_feature_df,cuisines_label_df,test_size=0.3)

Using linear SVC

In [4]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report, precision_recall_curve
import numpy as np

In [21]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import accuracy_score,precision_score,confusion_matrix,classification_report, precision_recall_curve
import numpy as np




C = 10
# Create different classifiers
classifiers = {
    'Linear SVC': SVC(kernel='linear',C=C,probability=True,random_state=0),
    'KNN classifier': KNeighborsClassifier(C),
    'SVC': SVC(),
    'RFST': RandomForestClassifier(n_estimators=100),
    'ADA': AdaBoostClassifier(n_estimators=100)
}

# Train your model using the Linear SVC and print out a report:
n_classifiers = len(classifiers)
for index, (name,classifier) in enumerate(classifiers.items()):
    classifier.fit(X_train,np.ravel(y_train))
    
    y_pred = classifier.predict(X_test)
    accuracy = accuracy_score(y_test,y_pred)
    print('Accuracy (train) for %s:%0.1f%%' % (name,accuracy * 100))
    print(classification_report(y_test,y_pred))

Accuracy (train) for Linear SVC:77.4%
              precision    recall  f1-score   support

     chinese       0.70      0.68      0.69       241
      indian       0.89      0.87      0.88       252
    japanese       0.76      0.71      0.74       224
      korean       0.82      0.78      0.80       252
        thai       0.70      0.82      0.76       230

    accuracy                           0.77      1199
   macro avg       0.77      0.77      0.77      1199
weighted avg       0.78      0.77      0.77      1199

Accuracy (train) for KNN classifier:70.7%
              precision    recall  f1-score   support

     chinese       0.68      0.66      0.67       241
      indian       0.86      0.80      0.83       252
    japanese       0.63      0.82      0.71       224
      korean       0.87      0.53      0.66       252
        thai       0.60      0.75      0.67       230

    accuracy                           0.71      1199
   macro avg       0.73      0.71      0.71      1199
weighted avg       0.73      0.71      0.71      1199

Accuracy (train) for SVC:80.5%
              precision    recall  f1-score   support

     chinese       0.74      0.71      0.72       241
      indian       0.91      0.90      0.91       252
    japanese       0.82      0.79      0.80       224
      korean       0.86      0.76      0.81       252
        thai       0.71      0.86      0.78       230

    accuracy                           0.80      1199
   macro avg       0.81      0.80      0.80      1199
weighted avg       0.81      0.80      0.81      1199

Accuracy (train) for RFST:82.2%
              precision    recall  f1-score   support

     chinese       0.79      0.75      0.77       241
      indian       0.90      0.90      0.90       252
    japanese       0.82      0.82      0.82       224
      korean       0.85      0.77      0.81       252
        thai       0.75      0.87      0.80       230

    accuracy                           0.82      1199
   macro avg       0.82      0.82      0.82      1199
weighted avg       0.82      0.82      0.82      1199

Accuracy (train) for ADA:71.1%
              precision    recall  f1-score   support

     chinese       0.63      0.47      0.54       241
      indian       0.89      0.84      0.86       252
    japanese       0.64      0.73      0.68       224
      korean       0.69      0.74      0.71       252
        thai       0.70      0.77      0.73       230

    accuracy                           0.71      1199
   macro avg       0.71      0.71      0.71      1199
weighted avg       0.71      0.71      0.71      1199

Using the random forest classifier

In [22]:
classifier = RandomForestClassifier(n_estimators=100)
classifier.fit(X_train,np.ravel(y_train))
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(f'Random Forest Accuracy (train): {accuracy * 100}')
print(classification_report(y_test,y_pred))

Random Forest Accuracy (train): 81.81818181818183
              precision    recall  f1-score   support

     chinese       0.77      0.76      0.77       241
      indian       0.89      0.90      0.90       252
    japanese       0.82      0.81      0.81       224
      korean       0.86      0.77      0.81       252
        thai       0.75      0.85      0.80       230

    accuracy                           0.82      1199
   macro avg       0.82      0.82      0.82      1199
weighted avg       0.82      0.82      0.82      1199

increasing estimator to 300

In [23]:
classifier = RandomForestClassifier(n_estimators=300)
classifier.fit(X_train,np.ravel(y_train))
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test,y_pred)
print(f'Random Forest Accuracy (train): {accuracy * 100}')
print(classification_report(y_test,y_pred))

Random Forest Accuracy (train): 82.98582151793161
              precision    recall  f1-score   support

     chinese       0.79      0.76      0.77       241
      indian       0.91      0.90      0.90       252
    japanese       0.84      0.83      0.83       224
      korean       0.87      0.79      0.83       252
        thai       0.76      0.87      0.81       230

    accuracy                           0.83      1199
   macro avg       0.83      0.83      0.83      1199
weighted avg       0.83      0.83      0.83      1199